const isLive=location.protocol==="http:";
function skyClock(value){if(!value)return "";const d=new Date(value);return Number.isNaN(d.getTime())?"":d.toLocaleString([],{day:"numeric",month:"short",hour:"2-digit",minute:"2-digit"});}
function artwork(uuid){return uuid?"https://images.metadata.sky.com/pd-image/"+encodeURIComponent(uuid)+"/16-9":"";}
function esc(s){return String(s??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]))}
async function refreshNow(){const p=document.querySelector("#skyNowLive");if(!p)return;const t=p.querySelector(".sky-programme"),m=p.querySelector(".sky-meta"),s=p.querySelector(".sky-synopsis"),b=p.querySelector(".sky-state");try{const r=await fetch("/api/sky/now",{cache:"no-store"}),d=await r.json();if(!d.available)throw 0;t.textContent=d.programme||d.channel||"Live TV";m.textContent=[d.channelno,d.channel].filter(Boolean).join(" · ");s.textContent=d.synopsis||"";b.textContent=d.live?"LIVE":"PLAYBACK";if(d.programmeuuid){p.style.setProperty("--now-artwork",'url("'+artwork(d.programmeuuid)+'")');p.classList.add("has-now-artwork")}}catch(e){t.textContent="Sky Q unavailable";m.textContent="";s.textContent="";b.textContent="UNKNOWN"}}
async function sendKey(key,button){if(!isLive)return;button.classList.add("sending");try{await fetch("/api/sky/key",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({key})});setTimeout(refreshNow,1200)}finally{setTimeout(()=>button.classList.remove("sending"),180)}}
document.querySelectorAll(".sport-now-controls [data-sky-key]").forEach(b=>b.addEventListener("click",()=>sendKey(b.dataset.skyKey,b)));
async function playRecording(id,button){if(!isLive||!id)return;button.classList.add("sending");try{const r=await fetch("/api/sky/recording/play",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({pvrid:id})});if(!r.ok)throw 0;setTimeout(refreshNow,1500)}catch(e){button.classList.add("failed");setTimeout(()=>button.classList.remove("failed"),1000)}finally{setTimeout(()=>button.classList.remove("sending"),180)}}
async function loadRecordings(){const grid=document.querySelector("#recordingsGrid"),count=document.querySelector("#recordingsCount");try{const r=await fetch("/api/sky/recordings",{cache:"no-store"}),d=await r.json(),items=d.recordings||[];count.textContent=items.length+" shown";grid.innerHTML=items.map(x=>'<button class="sport-channel recording-card" data-pvrid="'+esc(x.pvrid)+'">'+(x.programmeuuid?'<div class="recording-art" style="--rec-art:url(\''+artwork(x.programmeuuid)+'\')"></div>':'')+'<strong>'+esc(x.title||"Recording")+'</strong><div class="sport-onair"><span>'+esc(x.channel||"Sky Q")+(x.season?" · S"+esc(x.season)+(x.episode?" E"+esc(x.episode):""):"")+'</span><b>'+esc(x.synopsis||x.summary||"Recorded programme")+'</b><p class="sport-synopsis">'+esc([x.start?skyClock(x.start):"",x.status||""].filter(Boolean).join(" · "))+'</p></div></button>').join("");grid.querySelectorAll("[data-pvrid]").forEach(b=>b.onclick=()=>playRecording(b.dataset.pvrid,b));}catch(e){count.textContent="Unavailable";grid.innerHTML='<div class="sky-search-hint">Could not read the Sky Q recordings list.</div>'}}
refreshNow();if(isLive)setInterval(refreshNow,15000);loadRecordings();