const isLive=location.protocol==="http:";
function skyClock(v){if(!v)return "";const d=new Date(v);return Number.isNaN(d.getTime())?"":d.toLocaleTimeString([],{hour:"2-digit",minute:"2-digit"});}
function programmeArtworkUrl(uuid){return uuid?"https://images.metadata.sky.com/pd-image/"+encodeURIComponent(uuid)+"/16-9":"";}
async function refreshNow(){const p=document.querySelector("#skyNowLive");if(!p)return;const t=p.querySelector(".sky-programme"),m=p.querySelector(".sky-meta"),s=p.querySelector(".sky-synopsis"),b=p.querySelector(".sky-state");try{const r=await fetch("/api/sky/now",{cache:"no-store"}),d=await r.json();if(!d.available)throw 0;t.textContent=d.programme||d.channel||"Live TV";m.textContent=[d.channelno,d.channel,[skyClock(d.start),skyClock(d.end)].filter(Boolean).join("–")].filter(Boolean).join(" · ");s.textContent=d.synopsis||"";b.textContent=d.live?"LIVE":"PLAYBACK";if(d.programmeuuid){p.style.setProperty("--now-artwork",'url("'+programmeArtworkUrl(d.programmeuuid)+'")');p.classList.add("has-now-artwork");}}catch(e){t.textContent="Sky Q unavailable";m.textContent="";s.textContent="";b.textContent="UNKNOWN";}}
async function sendKey(key,button){if(!isLive)return;button&&button.classList.add("sending");try{await fetch("/api/sky/key",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({key})});setTimeout(refreshNow,1200);}finally{button&&setTimeout(()=>button.classList.remove("sending"),180);}}
document.querySelectorAll(".sport-now-controls [data-sky-key]").forEach(b=>b.addEventListener("click",()=>sendKey(b.dataset.skyKey,b)));
async function tune(channel){if(!isLive)return;await fetch("/api/sky/channel",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({channel:String(channel)})});closeSearch();setTimeout(refreshNow,1700);}
const overlay=document.querySelector("#skySearchOverlay"),input=document.querySelector("#skySearchInput"),results=document.querySelector("#skySearchResults"),keyboard=document.querySelector("#skyKeyboard");
function openSearch(){overlay.hidden=false;requestAnimationFrame(()=>overlay.classList.add("open"));input.value="";renderResults([],"");}
function closeSearch(){overlay.classList.remove("open");setTimeout(()=>overlay.hidden=true,120);}
document.querySelector("#skySearchOpen").addEventListener("click",openSearch);document.querySelector("#skySearchClose").addEventListener("click",closeSearch);overlay.addEventListener("click",e=>{if(e.target===overlay)closeSearch();});
["QWERTYUIOP","ASDFGHJKL","ZXCVBNM"].forEach(row=>{const r=document.createElement("div");r.className="sky-keyboard-row";[...row].forEach(ch=>{const b=document.createElement("button");b.type="button";b.textContent=ch;b.onclick=()=>type(ch);r.appendChild(b)});keyboard.appendChild(r)});
const bottom=document.createElement("div");bottom.className="sky-keyboard-row sky-keyboard-bottom";[["SPACE"," "],["⌫","BACK"],["CLEAR","CLEAR"]].forEach(([label,val])=>{const b=document.createElement("button");b.type="button";b.textContent=label;b.className=label==="SPACE"?"space":"";b.onclick=()=>type(val);bottom.appendChild(b)});keyboard.appendChild(bottom);
let timer;function type(v){if(v==="BACK")input.value=input.value.slice(0,-1);else if(v==="CLEAR")input.value="";else input.value+=v;searchSoon()}function searchSoon(){clearTimeout(timer);timer=setTimeout(searchSky,180)}
async function searchSky(){const q=input.value.trim();if(!q){renderResults([],"");return}results.innerHTML='<div class="sky-search-hint">Searching…</div>';try{const r=await fetch("/api/sky/search?q="+encodeURIComponent(q),{cache:"no-store"}),d=await r.json();renderResults(d.results||[],q)}catch(e){results.innerHTML='<div class="sky-search-hint">Search unavailable</div>';}}
function esc(s){return String(s??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]))}
function renderResults(items,q){if(!q){results.innerHTML='<div class="sky-search-hint">Start typing to search channels and programmes.</div>';return}if(!items.length){results.innerHTML='<div class="sky-search-hint">No matches for “'+esc(q)+'”</div>';return}results.innerHTML=items.slice(0,8).map(x=>'<button class="sky-search-result" data-channel="'+esc(x.channelno)+'">'+(x.logo?'<img src="'+esc(x.logo)+'" alt="">':'')+'<span><strong>'+esc(x.matchprogramme||x.programme||x.channel)+'</strong><small>'+esc(x.channelno)+' · '+esc(x.channel)+(x.matchtype==="next"?" · NEXT "+esc(skyClock(x.matchstart)):"")+'</small></span><em>Watch</em></button>').join("");results.querySelectorAll("[data-channel]").forEach(b=>b.onclick=()=>tune(b.dataset.channel))}
input.addEventListener("input",searchSoon);refreshNow();if(isLive)setInterval(refreshNow,15000);
const pad=document.querySelector("#channelPadOverlay"),padOpen=document.querySelector("#channelPadOpen"),padClose=document.querySelector("#channelPadClose"),padDisplay=document.querySelector("#channelPadDisplay"),padGo=document.querySelector("#channelPadGo"),padClear=document.querySelector("#channelPadClear");let padValue="";
function renderPad(){if(padDisplay)padDisplay.textContent=padValue||"—"}function openPad(){padValue="";renderPad();pad.hidden=false;requestAnimationFrame(()=>pad.classList.add("open"))}function closePad(){pad.classList.remove("open");setTimeout(()=>pad.hidden=true,120)}
padOpen&&padOpen.addEventListener("click",openPad);padClose&&padClose.addEventListener("click",closePad);padClear&&padClear.addEventListener("click",()=>{padValue="";renderPad()});document.querySelectorAll("[data-pad-digit]").forEach(b=>b.onclick=()=>{if(padValue.length<4){padValue+=b.dataset.padDigit;renderPad()}});document.querySelectorAll("[data-pad-key]").forEach(b=>b.onclick=()=>sendKey(b.dataset.padKey,b));padGo&&padGo.addEventListener("click",()=>{if(padValue)tune(padValue)});